ALTER TABLE users ADD deleted BIT NOT NULL DEFAULT 0;
ALTER TABLE users ADD create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD create_user_id BIGINT DEFAULT NULL;
ALTER TABLE users ADD update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE users ADD update_user_id BIGINT DEFAULT NULL;

ALTER TABLE users ADD CONSTRAINT users_fk_01 FOREIGN KEY (create_user_id) REFERENCES users(id);
ALTER TABLE users ADD CONSTRAINT users_fk_02 FOREIGN KEY (update_user_id) REFERENCES users(id);